version: "3.5"
networks:
  my-network:
    driver: bridge
    name: trung-network

services:
  my-api:
    container_name: api-nodejs
    build:
      context: ./api/
      dockerfile: Dockerfile
    hostname: apiserver
    volumes:
      - ./api:/var/www/code/api
      - /var/www/code/api/node_modules/
    ports:
      - 7000:7000

    networks:
      - my-network

  my-web:
    container_name: web-nodejs
    build:
      context: ./web/
      dockerfile: Dockerfile
    hostname: webserver
    volumes:
      - ./web:/var/www/code/web
      - /var/www/code/web/node_modules/
    ports:
      - 3000:3000
    networks:
      - my-network
  
  mongo:
    container_name: my-mongodb
    image: mongo
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - my-network

  mongo-express:
    container_name: my-mongodb-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - my-network